### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by iamRushikesh2342001** [ganraj21/Dental_Clinic#2]
please provide details about why login and registration not working .and also give the details of database .

**Comment by ganraj21** [comment]
Login is working fine I see the status code ok. I want to add chatting feature so that I implement the login and registration but till  now it's structure is not ready so that if any user is perform login action I'm not navigating to chat page & also if you click on registration still it not navigating to registration route. I will implement this in next month.

**Comment by iamRushikesh2342001** [comment]
To start registration and logins what should I have to do and also about database which one are you using there and where is it located.

**Comment by iamRushikesh2342001** [comment]
can you provide that code except with working chatting feature and all remaining working

**Comment by ganraj21** [comment]
but chatting feature is not build I will take this task next month then this option is available on the same repo.

**Comment by ganraj21** [comment]
> To start registration and logins what should I have to do and also about database which one are you using there and where is it located.
